resources:
  - name: static
    type: server
    replicas: 1
    containers:
      - name: portfolio
        image: ghcr.io/tim-ings/portfolio
        tag: 1.8.1
        ingress:
          public:
            hostname: test.tim-ings.com
            pathPrefix: /
          containerPort: 3000
