name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Set up git
        run: git config user.name "Tim Ings" && git config user.email "tim@tim-ings.com"

      - name: Install dependencies
        run: yarn

      - name: Deploy to github pages
        run: yarn deploy
