name: Deploy

on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Deploy to github pages
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          git remote set-url origin git@github.com:${{ secrets.GITHUB_REPOSITORY }}.git
          git config --global user.name "Tim Ings"
          git config --global user.email "tim@tim-ings.com"
          yarn
          yarn deploy
